### ISSUE TITLE
Create Base UI Layout for In-Game Debugging

### ISSUE THREAD

**Issue by DarthMarino** [SentinelsLabs-Gamedev/castle-inquisitors#3]
### Expectations
Design and implement a base UI layout for in-game debugging.
Include essential debugging elements such as FPS counter, memory usage, and relevant game state information.
Ensure the UI is non-intrusive and can be toggled on/off easily.

### Notes
Refer to the [Unreal Engine UI UMG Documentation](https://docs.unrealengine.com/en-US/Engine/UMG) for best practices and guidelines.
Consider using the Debug Draw system for additional visual debugging tools.
Check out best practices guide on the [Unreal Engine UMG Best Practices](https://www.unrealengine.com/fr/tech-blog/umg-best-practices).

**Comment by PseudoMera** [comment]
https://benui.ca/unreal/visual-logger/
